"""add publish tables

Revision ID: 259d25e976f9
Revises: fe9ff2ebac28
Create Date: 2024-06-27 21:25:38.820850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259d25e976f9'
down_revision: Union[str, None] = 'fe9ff2ebac28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_campaign',
    sa.Column('eid', sa.String(), nullable=False),
    sa.Column('year', sa.Unicode(length=4), nullable=True),
    sa.Column('name', sa.Unicode(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    schema='publishmgr'
    )
    op.create_table('publish_departament',
    sa.Column('eid', sa.String(), nullable=False),
    sa.Column('code', sa.Unicode(length=10), nullable=True),
    sa.Column('name', sa.Unicode(length=120), nullable=True),
    sa.Column('comercial_group_eid', sa.Unicode(length=120), nullable=True),
    sa.Column('store_code_legal', sa.Unicode(length=6), nullable=True),
    sa.Column('store_code_natural', sa.Unicode(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    schema='publishmgr'
    )
    op.create_table('publish_specialists',
    sa.Column('eid', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(length=24), nullable=False),
    sa.Column('code', sa.Unicode(length=10), nullable=True),
    sa.Column('publish_departament_eid', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['publish_departament_eid'], ['publishmgr.publish_departament.eid'], ),
    sa.PrimaryKeyConstraint('eid'),
    sa.UniqueConstraint('user_name'),
    schema='publishmgr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_specialists', schema='publishmgr')
    op.drop_table('publish_departament', schema='publishmgr')
    op.drop_table('publish_campaign', schema='publishmgr')
    # ### end Alembic commands ###
