"""add initial table

Revision ID: fe9ff2ebac28
Revises: 
Create Date: 2024-06-11 18:28:05.209664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe9ff2ebac28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_rel_operations_categories',
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('operation_category_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('operation_type', 'operation_category_name'),
    schema='accountingentrymgr'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting_rel_operations_categories', schema='accountingentrymgr')
    # ### end Alembic commands ###
